### ISSUE TITLE
Get rid of inline styles

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#114]
There are 38 inline styles in `index.html.in`. They should be eliminated to enable to the `inline-style-disabled` HTMLHint rule.

**Comment by share-with-me** [comment]
Created a PR #117 . Please have a look @sushain97

**Comment by idealadarsh** [comment]
@sushain97 I'd like to work on this issue.

**Comment by shardulc** [comment]
@sushain97 Fix with #214, should be closed.

**Comment by sushain97** [comment]
Not yet, unfortunately!
