### ISSUE TITLE
Better testing

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#116]
Unit tests on multiple browsers through Travis CI would be ideal.

**Comment by share-with-me** [comment]
@sushain97  I made use of `QUnit` unit testing framework for Javascript to make simple unit tests to determine if the browser supports SRI. My test works like this, I try to load a webpage with wrong `integrity` value of the `bootstrap cdn` and then check by using some bootstrap specific function if the bootstrap script has loaded. The `assert` test then is - if the function returns `true` (implying that script has loaded inspite of wrong integrity) - the test case of `Browser does not support SRI` would work else `Browser Supports SRI` (ie the browser would not load if wrong integrity).  I will now work on understanding how Travis-CI actually works and find a way to do this test cross-browser (may be by applying a list of browsers as JSON list or something. Have to figure that out as I am new to it). The test is a success on Chrome and Firefox but fails on Safari. 

Following are the screenshots.

![screen shot 2017-03-17 at 8 33 02 am](https://cloud.githubusercontent.com/assets/8894636/24027388/343fd238-0aed-11e7-9d1e-0c6420791426.png)
![screen shot 2017-03-17 at 8 33 24 am](https://cloud.githubusercontent.com/assets/8894636/24027396/3d48f04e-0aed-11e7-8d0f-d75c0445bf34.png)
![screen shot 2017-03-17 at 8 34 39 am](https://cloud.githubusercontent.com/assets/8894636/24027434/97f845b2-0aed-11e7-9aa7-7f4529f9a28c.png)

**Comment by sushain97** [comment]
Nice work @share-with-me! I wonder if it can be integrated with Travis nicely...

On another note, our priority isn't to make sure that features like SRI work since this is already [documented](https://developer.mozilla.org/en-US/docs/Web/Security/Subresource_Integrity#Browser_compatibility). The focus is to make sure translation, generation, switching locales, etc. works correctly.

**Comment by share-with-me** [comment]
@sushain97  Awesome! The documentation takes care of SRI stuff. Now that the environment is set, setting any kind of tests for the features should not be that difficult! So when you say translation, generation, etc, we are looking at the technical  part of it right? As in whether the the `originalText` on clicking translate yielded an output in `translatedText` and not getting concerned with the semantics or checking how correct the translation is?

**Comment by sushain97** [comment]
@share-with-me exactly. Other related things like making sure you can use the language drop downs, etc. UI testing appears to be quite tricky. I've never messed with it much myself :)

**Comment by share-with-me** [comment]
@sushain97 Ohh. This is surely a big thing than I anticipated. Need to plan of the UI elements to be tested and design the way they need to be done. I will think over this and discuss the <feature, strategy> points with you!

**Comment by JPJPJPOPOP** [comment]
@sushain97 

Found something interesting relating to this: https://github.com/Krinkle/travis-ci-node-and-browser-qunit

Might try doing this task later :D

**Comment by sushain97** [comment]
Cool! Testing in Node is fine. We're using Circle for this project but it's basically the same as Travis. It's already set up with Node as well.

**Comment by sushain97** [comment]
On `master`, we have 40% test coverage using Jest. Next step in this saga is https://github.com/apertium/apertium-html-tools/issues/409.
