### ISSUE TITLE
More dynamically configurable options

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#158]
We have lots of constants inside the application but most of them aren't accessible through `config.conf`. We might want to figure out a more dynamic approach to this rather than adding a line to `read-conf.py` for each new constant.

**Comment by shardulc** [comment]
Recreating relevant comments:

My idea:
>  - every single constant in `read-conf.py` has a fallback whose value is the default for html-tools (i.e. the values that we know to work)
>  - every single line in the file `advanced-config.conf` is commented, and some text explains how you would customize the constants by uncommenting and changing them
> 
> This means we will technically be providing an empty `advanced-config.conf` file which will make everything work by default, and users can change things if they want to by uncommenting lines in it. In fact, now we can even call the file `advanced-config.conf.example` and say that it should be copied to `advanced-config.conf` if you want to make changes, so that simple git pulls will not override customizations.
>
>Only goavki would modify the Python when required to tweak constants. If downstream users want to tweak constants, they'd be recommended to create/change `advanced-config.conf` instead so that they can keep their tweaks even when we push different fallbacks. (Changing the conf file does not require a developer either.)

@sushain97's rebuttal:
> I actually don't like that approach too much because it requires editing a Python file to change the interface. I think it makes everything a little too connected and feels very magical.
>
> A developer would have to modify the Python to change how the interface looks by default. This seems not great to me with regards to separation of concerns. Fundamentally, the difference between these two configurations is that one can have empty values and the other must always be complete.
>
> This is my issue because we lose separation of concerns. Right now the Python is just a tool without any semantic meaning (it has fallbacks but those are duplicated in `config.conf.example`). If we implemented this idea, this would no longer be the case. We could store the defaults in the JS and hydrate the configuration with those defaults when they're missing, i.e. `advanced-config.conf.example` would have commented out constants and it could be moved to `advanced-config.conf`.

**Comment by shardulc** [comment]
Right now, the plan I'm most comfortable with is:
 - `advanced-config.conf` under version control with the defaults we want
 - `read-conf.py` with fallbacks duplicating `advanced-config.conf`
 - `config.conf` as before

@sushain97 What do you think?

**Comment by sushain97** [comment]
On `master`, the config is all stored/processed in TS so this isn't much of a problem anymore. It's ~trivial to make anything a config option.
