### ISSUE TITLE
Fail more gracefully when APy is down

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#207]
currently the interface looks incorrectly aligned...

see #206 for screenshots

**Comment by Androbin** [comment]
@sushain97 Do you have suggestions for an appropriate error message and how to display it?

**Comment by sushain97** [comment]
Ideally, none. Everything should just respond with no translation available.

**Comment by Androbin** [comment]
What do we know yet about the cause of the layout issue?
I'd suspect that some part of the script gets stuck during a DOM modification.

**Comment by sushain97** [comment]
Nothing as far as I know.

**Comment by Androbin** [comment]
Which parts of the initial DOM construction could be blocked when APy is down?
Which parts of a fresh page are generated by code that's interlaced with networking code?

**Comment by sushain97** [comment]
I don't carry all this information in my head. Figuring it out would be
part of fixing the issue.

On Dec 27, 2017 9:29 AM, "Robin Richtsfeld" <notifications@github.com>
wrote:

Which parts of the initial DOM construction could be blocked when APy is
down?
Which parts of a fresh page are generated by code that's interlaced with
networking code?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/goavki/apertium-html-tools/issues/207#issuecomment-354129745>,
or mute the thread

**Comment by Androbin** [comment]
> I don't carry all this information in my head. Figuring it out would be part of fixing the issue.

No deal, it'd just be wasted effort if you had some idea.

**Comment by sushain97** [comment]
This should no longer be an issue on `master`. The UI renders completely independently of any network requests.
