### ISSUE TITLE
Manually downloading translated documents generates a weird filename

### ISSUE THREAD

**Issue by myfrom** [apertium/apertium-html-tools#221]
**How to reproduce?**
Right-click the download link after translating a document and click "Save target as..."

**Expected behaviour**
The default filename is same as uploaded file or something default such as 'translated.txt'.

**Actual behavior**
The default filename is a weird string.

**Affected browsers**
All that don't support `download` attribute in `<a>` tag.
[caniuse](https://caniuse.com/#feat=download)

**Comment by diogoscf** [comment]
If a browser doesn’t support the `download` attribute, and you use “Save target as...” it will use the link to the file as the filename, which is a weird string due to the way the link is created.

**Comment by sushain97** [comment]
Indeed, that's what we gathered. However, we're not sure how to fix it (or
if it's even possible).

>

**Comment by diogoscf** [comment]
It’s theoretically possible, but **HARD**, as explained [here](https://stackoverflow.com/a/41947861/7729429).

**Comment by sushain97** [comment]
We no longer support IE11.
