### ISSUE TITLE
"Multi-step translation" option glitches on RTL

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#246]
![image](https://user-images.githubusercontent.com/4211838/34470747-042bad42-eefe-11e7-9c23-b0909865ac25.png)

**Comment by shuchita-g1** [comment]
No description provided. need bit of help to solve this

**Comment by sushain97** [comment]
@shuchita-g1, Take a look at how the "Multi step translation (experimental)" option looks on beta.apertium.org and compare to how it looks in my screenshot. It should be flush with the left edge and the parens should be around experimental.
