### ISSUE TITLE
Bug in displaying navbar with one item

### ISSUE THREAD

**Issue by JPJPJPOPOP** [apertium/apertium-html-tools#258]
In `config.conf`, set `SHOW_NAVBAR = True` but with only one mode `ENABLED_MODES`.

It ends up like this:
![screen shot 2018-01-06 at 10 31 10 pm](https://user-images.githubusercontent.com/13565154/34647243-05071048-f332-11e7-8d63-32b44e4a4ec3.png)

**Comment by likhitgrandhi** [comment]
hey @sushain97 , i did replicate the above scenario, i dont understand the expected result of the fix. Im sorry if im being too noob.

**Comment by sushain97** [comment]
Take a look at how the navbar looks on beta.apertium.org

**Comment by likhitgrandhi** [comment]
![screenshot from 2018-03-09 16-08-34](https://user-images.githubusercontent.com/13435169/37203602-3a8ec6f4-23b4-11e8-95e7-e5f1201fe89c.png)
hey @sushain97, would this be an appropriate fix for the above issue ? or should there still be a change in the positioning of the menu item ?

**Comment by sushain97** [comment]
The position looks really strange... left align seems better.

**Comment by JPJPJPOPOP** [comment]
The problem is actually that the navbar is sometimes small enough (depends which modes are enabled) to fit in a gap between the Apertium sign and the locale select drop down.

![screen shot 2018-06-14 at 8 05 31 pm](https://user-images.githubusercontent.com/13565154/41448281-9a5489c4-700e-11e8-88e3-d48ef66d6083.png)

**Comment by sushain97** [comment]
![image](https://user-images.githubusercontent.com/4211838/117561569-cb50b800-b04c-11eb-8158-7b5821960387.png)
appears fixed on master
