### ISSUE TITLE
Fix build

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#297]
https://circleci.com/gh/apertium/apertium-html-tools/502

**Comment by mrcolo** [comment]
I can work on this!

**Comment by sushain97** [comment]
@mrcolo, sounds good! Send a PR.

**Comment by sushain97** [comment]
@mrcolo my apologies for taking care of this instead of letting you. It was a very simple change and I don't like the build to be broken for too long. There are many other issues in this repo tagged as `beginner` that it would be great if you could take a look at!

**Comment by mrcolo** [comment]
Sure! Will do!
