### ISSUE TITLE
Organize HTML into a folder

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#312]

**Comment by satya-vinay** [comment]
Sorry,but Can you please explain it more properly?

**Comment by sushain97** [comment]
Which part of it?

**Comment by sushain97** [comment]
A top-level directory would be fine for HTML.

**Comment by satya-vinay** [comment]
fine then I will create a directory HTML and add the following files there:
prod-head.html
not-found.html
debug-head.html

Anything else should I add there?

**Comment by sushain97** [comment]
I'm thinking we might as well add `index.html.in` as well.
