### ISSUE TITLE
Not found banner placement is wrong

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#329]
Current DOM:

![image](https://user-images.githubusercontent.com/4211838/45606132-648fb380-b9f7-11e8-9969-97ef6eba98a7.png)

Current Placement:

![image](https://user-images.githubusercontent.com/4211838/45606125-56da2e00-b9f7-11e8-8a53-ed87d474f4ed.png)

Correct DOM:

![image](https://user-images.githubusercontent.com/4211838/45606091-1e3a5480-b9f7-11e8-9c17-80eb32dae351.png)

Correct Placement:

![image](https://user-images.githubusercontent.com/4211838/45606107-41fd9a80-b9f7-11e8-8b50-376155687db3.png)

**Comment by lexcorp16** [comment]
hi @sushain97 I would like to take a look at this. How can you help get started

**Comment by sushain97** [comment]
@lexcorp16 have you cloned the repository and built it?

**Comment by milanandreew** [comment]
@lexcorp16 are you still interested in this issue?
I'd be more than happy to take it over.

**Comment by milanandreew** [comment]
@sushain97 
how to replicate this issue?
thanks in advance

**Comment by sushain97** [comment]
@milanandreew e.g. http://beta.apertium.org/not-found.html

**Comment by milanandreew** [comment]
Only the beta has this issue.

**Comment by milanandreew** [comment]
Right?

**Comment by xavivars** [comment]
When is this banner shown?

**Comment by sushain97** [comment]
You should configure your webserver to send 404 to this page.

**Comment by milanandreew** [comment]
Just for clarification: This repository is responsible for https://apertium.org/ right?
Not for the beta.apertium.org link?
Because my build works just fine.

**Comment by sushain97** [comment]
It's responsible for both.

**Comment by milanandreew** [comment]
Beta:
![screencapture-beta-apertium-org-index-eng-html-2018-11-09-21_48_33](https://user-images.githubusercontent.com/43289010/48289792-f6082880-e470-11e8-9f26-0b9304be2d7e.png)
My build (and apertium.org/translate):
![screencapture-localhost-8082-build-index-eng-html-2018-11-09-21_48_48](https://user-images.githubusercontent.com/43289010/48289803-04eedb00-e471-11e8-8e44-d2f546d3aacb.png)

**Comment by milanandreew** [comment]
So how can we replicate the issue?

**Comment by sushain97** [comment]
Ah, this doesn't seem to happen with all configs. Try this one:

```
[APY]
HTML_URL = https://www.apertium.org
APY_URL = http://beta.apertium.org/apy

SUBTITLE = Beta
SUBTITLE_COLOR = #dc2926

# Set ALLOWED_* and ENABLED_* configuration parameters to undefined for all (no filtering)
ALLOWED_LANGS =
ALLOWED_VARIANTS =

# Available modes are currently 'translation', 'analyzation', 'generation', 'spellchecking, 'sandbox'
ENABLED_MODES = translation, analyzation, generation
DEFAULT_MODE = translation

# Whether or not to enable chained translations
TRANSLATION_CHAINING = True

SHOW_NAVBAR = True

#PIWIK_SITEID = 1
#PIWIK_URL = http://apertium.org/piwik

# Expiry times are in hours (set them to 0 for no caching)
LIST_REQUEST_CACHE_EXPIRY = 24
LANGUAGE_NAME_CACHE_EXPIRY = 24
LOCALIZATION_CACHE_EXPIRY = 24
AVAILABLE_LOCALES_CACHE_EXPIRY = 24

# Localisation replacement strings, see assets/strings/*.json for usage:
[REPLACEMENTS]
maintainer = <a href='http://wiki.apertium.org/wiki/Apertium' target='_blank' rel='noopener'>Apertium</a>
```

**Comment by milanandreew** [comment]
thx

**Comment by milanandreew** [comment]
I mean, it works, but I can't replicate the issue.

**Comment by sushain97** [comment]
Alas, not sure how to help since I can replicate it fine if I use that config with master and directly go to `not-found.html`.

**Comment by milanandreew** [comment]
Yep.

**Comment by milanandreew** [comment]
Do you have jsmin and csscompressor installed?

**Comment by milanandreew** [comment]
So this is a minification issue.

**Comment by milanandreew** [comment]
Question: Is html/js/css minififcation really necessary?

**Comment by milanandreew** [comment]
I mean, I get trying to size down files for slow internet connections.

**Comment by milanandreew** [comment]
I don't think it is...
After pip install -r and all that it still shows up where it should be.

**Comment by milanandreew** [comment]
Yes it is a lint issue, forgot to delete old build directory.
Works on my vm.

**Comment by sushain97** [comment]
Or within our faulty input to it. I would ensure the HTML validates.

**Comment by milanandreew** [comment]
On it.

**Comment by milanandreew** [comment]
I couldn't find anything.

**Comment by himanshuc3** [comment]
@sushain97 Is this project available for GSOC 2019.

**Comment by sushain97** [comment]
@himanshuc3 that's a function of whether Apertium is accepted to GSoC which is not yet decided.

**Comment by sharad-99** [comment]
The error is not showing up in my browser.

**Comment by sushain97** [comment]
The issue does not appear unless the config above is used along with the minifiers.

**Comment by snehitha211** [comment]
> @lexcorp16 are you still interested in this issue?
> I'd be more than happy to take it over.

i'm very much interested in this. can u please help me get started.

**Comment by Popeyes-bit** [comment]
is this issue still open? i can work on it ....

**Comment by sushain97** [comment]
This feature no longer exists.
