### ISSUE TITLE
Not found pages return a HTTP status code of 200

### ISSUE THREAD

**Issue by xavivars** [apertium/apertium-html-tools#330]
Pages that doesn't exist (i.e. apertium.org/not-found.html) should, on top of displaying a banner saying the page doesn't exist, return a 404 status code. Currently, a 200 is sent to the browser.

**Comment by sushain97** [comment]
The not found page itself should display a 200 if you access it directly. Your web server should redirect to the not found page with a 400. This isn't a role that html-tools plays. It's just a function of your web server.

**Comment by sushain97** [comment]
That is, the page you're referring to _does exist_ :)

**Comment by xavivars** [comment]
I misunderstood how it was working :P

**Comment by xavivars** [comment]
BTW, is the redirect set up somewhere? Cound find it in beta.apertium.org

**Comment by xavivars** [comment]
(I'll delete the issue, it makes no sense)
