### ISSUE TITLE
æsthetic regressions in analyser

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-html-tools#331]
An older version of html-tools at http://turkic.apertium.org/ (1) formats the output of morphological analysis nicely.  A more recent version at http://beta.apertium.org/ (2) has lost a lot of the things that not just made the formatting nice, but made the output usable.  These regressions include:
* vertical alignment of form and analysis
* highlighting of hovered cohort
* horizontal lines between cohorts.

(1) 
![2018-11-14-01 10 46_001](https://user-images.githubusercontent.com/963849/48463655-d479aa80-e7aa-11e8-9652-36119d52a1a9.png)

(2)
![2018-11-14-01 12 24_001](https://user-images.githubusercontent.com/963849/48463661-d7749b00-e7aa-11e8-8d5a-7a0e1a9963bb.png)

**Comment by sushain97** [comment]
root cause: https://github.com/ jquery/jquery/issues/1835
