### ISSUE TITLE
Language dropdowns bug in RTL locales

### ISSUE THREAD

**Issue by myfrom** [apertium/apertium-html-tools#333]
The language dropdowns in translate mode (both target and input) don't span into multiple columns on smaller screens when using RTL locale. This seems to be a JS bug.

## Expected behaviour:

Span correctly into multiple columns like on eg. English locale

![apertium bug ltr](https://user-images.githubusercontent.com/19410489/48983810-e553e580-f0f3-11e8-8b9d-23397477a92e.png)

## Actual behaviour:

All languages go into one or two columns which are often longer than the viewport height

![apertium bug rtl](https://user-images.githubusercontent.com/19410489/48983817-0d434900-f0f4-11e8-8be6-b734c6f7fd8c.png)

**Comment by sharad-99** [comment]
Is it done? It is behaving normally in my browser.

**Comment by sushain97** [comment]
No. This bug is still an issue with RTL localizations and a relatively small viewport.
