### ISSUE TITLE
More intelligent default pair

### ISSUE THREAD

**Issue by sushain97** [apertium/apertium-html-tools#343]
Currently, we default to the first available pair. It would be nicer to default to something based on the user's locale.

**Comment by IlnarSelimcan** [comment]
Say, the language listed first in browser's preferences as the default target language.

**Comment by jonorthwash** [comment]
Moving on down to other languages if that's not available.

**Comment by MaathavanJkr** [comment]
Down to other languages? you mean English?

**Comment by jonorthwash** [comment]
> Down to other languages? you mean English?

No, I mean other languages the person has listed in their browser preferences.

**Comment by MaathavanJkr** [comment]
> > Down to other languages? you mean English?
> 
> No, I mean other languages the person has listed in their browser preferences.

Okay! Got it! :)
