### ISSUE TITLE
Use material design?

### ISSUE THREAD

**Issue by scoopgracie** [apertium/apertium-html-tools#350]
Should we switch to a Material Design interface?

**Comment by sushain97** [comment]
html-tools already supports theming, some of them being relatively "material design"y (see the wiki for details). More important than the UI is switching the site away from jQuery to something like Preact or VueJS. The amount of features the site has now has outgrown jQuery and it's quite hard to add new things without breaking old ones or understanding some pretty convoluted code.

**Comment by scoopgracie** [comment]
Should we add "Migrate off jQuery" as an issue? And maybe a GCI task?

**Comment by sushain97** [comment]
Sure, an issue is fine. There are related ones open.

It isn't GCI task sized. Would take at least week or two.

**Comment by scoopgracie** [comment]
OK. Should I open it?
