### ISSUE TITLE
Migrate off jQuery

### ISSUE THREAD

**Issue by kj7rrv** [apertium/apertium-html-tools#351]
The site has outgrown jQuery. We need to migrate off. Not sure how we make decisions here, but we will need to either choose a new framework or choose to not use one.

**Comment by sushain97** [comment]
No framework isn't really a viable option.

**Comment by TinoDidriksen** [comment]
Outgrown jQuery? Goodness no. jQuery is alive and well, and unlike all the other fly-by-night new-every-week JS frameworks, it just works and is maintained. I say that project using other JS frameworks would be better off moving to jQuery.

**Comment by sushain97** [comment]
The state management in this project is pretty complicated. There's no way to test it sanely and nothing is remotely broken up into components. Feel free to try messing with some of the core translation bits or writing meaningful tests. 

It needs a rewrite in something more suited to dealing with complex state. We don't need Redux or any of the more complicated libraries but something simple like Preact would make it significantly better. Sure, there are lots of ephemeral JS libraries out there but ones like React have proven their value.

jQuery works just fine, until a point.

**Comment by sushain97** [comment]
Moving away from jQuery would also make it more accessible to younger contributors that are often unfamiliar with or haven't even heard of jQuery.

**Comment by scoopgracie** [comment]
Do we need to use a framework at all?

**Comment by sushain97** [comment]
jQuery is hardly a framework. It's more a set of utility functions. The biggest thing it gets us is something that is a "framework", Bootstrap.

**Comment by sushain97** [comment]
I don't feel bad about saying this about the current state of the code since 90% of it is my fault. I'm sure that it could have been written better but the imperative style of programming that jQuery encourages just doesn't work well with complex user interfaces that are better programmed "functionally". Having to think about how your change will potentially impact every single other piece of the user interface is unsustainable and makes further development on this project pretty difficult even for someone who wrote most of the current code. Perhaps it could be completely rewritten to be more modular using only jQuery but if we're going to do a complete rewrite, jQuery isn't the right choice IMO. I'm definitely not voting for something like Angular but Preact/React aren't particularly difficult to pick up and offer lots of advantages. It's possible to use these frameworks without also succumbing to the 2GB `node_modules` + 10m webpack build effect.

**Comment by scoopgracie** [comment]
OK, so it sounds like React/Preact is the best choice?

**Comment by sushain97** [comment]
That's what I would vote for but I'm open to other suggestions.

**Comment by scoopgracie** [comment]
Would doing it framework-less be OK?

**Comment by sushain97** [comment]
I don't think that's a good idea. It offers basically nothing over using jQuery. The jQuery dependency is pretty light.

**Comment by scoopgracie** [comment]
Do we want to use react or preact?

**Comment by scoopgracie** [comment]
also, if I do it, I have access to any major browser except Safari.

**Comment by scoopgracie** [comment]
Would doing this entail a complete rewrite of the frontend?

**Comment by scoopgracie** [comment]
Should I start working on  a React version locally?

**Comment by sushain97** [comment]
> Do we want to use react or preact?

I haven't looked closely enough in a while.

> Would doing this entail a complete rewrite of the frontend?

Basically.

> Should I start working on a React version locally?

This migration isn't really GCI shaped & I'm afraid I don't have the bandwidth right now to set up all the scaffolding to make it into bite-size tasks (if even possible). Note that it's not just the frontend code that needs to be rewritten, it would be the CI configs, the build/testing steps, the linting, the documentation and more.

**Comment by scoopgracie** [comment]
After we decide react/preact, is there any reason I can't start working on
it locally when I'm waiting for a mentor to accept GCI tasks? I would have
quite a bit of time that was not GCI.

**Comment by scoopgracie** [comment]
If small size and performance are important, Preact sounds like the better choice.

**Comment by scoopgracie** [comment]
It looks like either one needs node.js for a normal installation. However, it appears to be possible to avoid this.

**Comment by sushain97** [comment]
> After we decide react/preact, is there any reason I can't start working on
it locally when I'm waiting for a mentor to accept GCI tasks?

I can't stop you from trying! But really, I don't encourage it because I don't have the time to actively mentor an undertaking of this scope. There are a lot of "hidden" requirements.

> It looks like either one needs node.js for a normal installation. However, it appears to be possible to avoid this.

We'd have to produce compiled dist files. There can't be a runtime dependency on Node.

**Comment by sushain97** [comment]
Er, to clarify, the minified and compiled bundles + source maps would have to be checked in.

**Comment by scoopgracie** [comment]
What are dist files? I could pretty easily avoid the Node dependency. In fact, I could even make it static files if needed.

**Comment by scoopgracie** [comment]
I'm referring to doing it separately from GCI. Also, the minified and
compiled bundles of what?

**Comment by sushain97** [comment]
Static files aren't possible. This project needs a build step (check out what the current build steps do for context as to why).

The minified and compiled (technically, transpiled) versions of the ES6 for browsers.

There's already a Node dependency here for development, just not for building it. There's no sensible way to get rid of it.

**Comment by scoopgracie** [comment]
I meant it would build to static files.

**Comment by sushain97** [comment]
Sure. That's really the only way (and what we do right now) aside from SSR which we're definitely not doing.

**Comment by scoopgracie** [comment]
What's SSR?

**Comment by sushain97** [comment]
server-side rendering

**Comment by scoopgracie** [comment]
Ok, thanks!

**Comment by xavivars** [comment]
I'd jump in (but please take this just as an opinion). I've been recently (past few months) working quite a lot with GatsbyJS, a "static site generator" based on react.

Pros
- super easy to start 
- handles a ton of stuff for you (build pipeline, etc) 
- generates REALLY fast websites 
- easy to move to another react-based framework if required
- AMAZING open source community
- really cool features (graphql, etc) 

Cons
- very opinionated 

I won't be able to support as a mentor the rewrite of Apertium's website as a GCI task (requires planning and breaking up the work too much) but I'm happy to help guiding this outside GCI

**Comment by scoopgracie** [comment]
It won't really work as part of GCI anyway. It'll have to be separate due to the size of the task.

**Comment by sushain97** [comment]
I've heard of Gatsby before but haven't used it. It might be worth a try! However, I foresee a couple of complications:

- our build process is moderately wild (fetching from random HTTP services, editing input HTML, etc.) that might not mesh will with Gatsby's opinionated build framework.
- the transpiled code might have a bunch of boilerplate/React'y bloat in it and this project is currently relatively lightweight

**Comment by unhammer** [comment]
> - our build process is moderately wild (fetching from random HTTP
> services, editing input HTML, etc.) that might not mesh will with
> Gatsby's opinionated build framework.

https://www.gatsbyjs.org/ seems to suggest that pages can be rendered
from existing json/API sources. Server-side rendering sounds like a good
reason to at least look into Gatsby. In fact, reading about it, it
sounds like it does more or less what our Makefile does, just in a much
more maintainable manner =P

**Comment by xavivars** [comment]
I've been thinking about Apertium as a good use case for Gatsby for a few months now, but never mentioned it because I don't like proposing work and not being able to spend time on it, and also because of the amount of time spent on our own custom build.

But it's definitely worth giving it a try. 

Reading data at build time from static files (json, yml, Markdown,...) is straight forward, and it's also relatively easy to pull data from services.

**Comment by scoopgracie** [comment]
Won't the build process be replaced entirely in the migration process?

**Comment by scoopgracie** [comment]
Gatsby looks pretty good for this.

**Comment by scoopgracie** [comment]
I'm gonna work on a version, it'll be a good learning exercise for me anyway. It'll be under a permissive OSI-approved license, so Apertium can use it if it turns out good.

**Comment by unhammer** [comment]
> Won't the build process be replaced entirely in the migration process?

That'd be great =D 

(it feels more correct to call it a rewrite than migration …)

**Comment by scoopgracie** [comment]
Yeah, it isn't really a migration.

**Comment by scoopgracie** [comment]
Also, should I make it a PWA? It seems that that will be pretty easy with Gatsby.

**Comment by scoopgracie** [comment]
https://github.com/scoopgracie/apertium-site is the repo for my version. Right now, I haven't committed anything, so it's just a README and LICENSE (Apache 2, but I'm willing to relicense).

**Comment by scoopgracie** [comment]
I just thought... where are the translation files? I'll need them to continue.

**Comment by scoopgracie** [comment]
nvm, found them

**Comment by scoopgracie** [comment]
What browsers do we need to support? Last 2 versions of IE, Edge, Chrome, Safari, Firefox, and Opera?

**Comment by sushain97** [comment]
https://browserl.ist/?q=%3E+0.15%25 would be nice. It's a matter of determining what the bundle size tradeoffs look like.

**Comment by scoopgracie** [comment]
What market share of browsers do we need to support? 1-2%?

**Comment by sushain97** [comment]
I just linked directly to what I wanted.

**Comment by scoopgracie** [comment]
OK, thanks!

**Comment by scoopgracie** [comment]
Anyone who wants to contribute, see https://github.com/scoopgracie/apertium-site/issues/.

**Comment by sushain97** [comment]
Transposing my thoughts from an email conversation with @jonorthwash:

There are multiple axes where taking a 3rd party dependency/framework is useful.

1. Build system
Current approach: Makefile + Python scripts
Preferable approach: A JS bundler system like Webpack/Parcel/Rollup - GatsbyJS is just Webpack underneath as far as I can tell.
My opinion: Almost anything is better than what we have now. Really though, this stuff is relatively less likely to change once set up so it's not a huge deal if it's complicated. We've rolled our own and it ~works for now but is pretty complex.

2. UI framework
Current approach: Bootstrap
Preferable approach: I dunno, there are lots of options here. I personally like http://blueprintjs.com/ but it might be the wrong aesthetic for apertium.org. It also doesn't necessarily come with all the layout utilities we would want.
My opinion: We can probably go in lots of reasonable directions here. I would focus on A) something that will work with the JS framework and B) something that comes with all the things we need included. It's probably not a huge deal though, we can customize what we use and html-tools isn't _that_ complex as far as the UI components go. We should find something that supports all the Boostrap components we use now (alerts, notices, etc.).

3. JS framework
Current approach: jQuery
Preferable approach: React/Preact+JSX. Or even React+TypeScript potentially! Even Vue.JS is a possibility.
My opinion: If I were writing this scratch, I would use React + TypeScript. They both have huge communities and lots of folks that can work on html-tools. React also offers the libraries/built-in state-manangement/functional components structure that we would need to make html-tools more maintainable/less prone to bugs/more readable. IMO - We should not use plain JS with no JS framework. If we do, we might as well not rewrite at all.

**Comment by scoopgracie** [comment]
To me, one of the biggest advantages of vanilla JS is that we have one less
major dependency that will probably basically go away in ~5 years. It's
possible that React will stay popular indefinitely, but I doubt it.

**Comment by scoopgracie** [comment]
Also, for the UI design, I personally would like Material Design.

**Comment by sushain97** [comment]
> To me, one of the biggest advantages of vanilla JS is that we have one less
major dependency that will probably basically go away in ~5 years. It's
possible that React will stay popular indefinitely, but I doubt it.

React and even jQuery will still have communities behind them for the next decade, at least. They may get smaller but they'll still be there and that alone isn't a particularly strong argument for not building a more maintainable codebase.

**Comment by sushain97** [comment]
> Also, for the UI design, I personally would like Material Design.

Sure. I'd take a straw poll.

**Comment by scoopgracie** [comment]
I really don't see why a Web framework is needed for maintainability. Also,
my current work is at https://github.com/scoopgracie/apertium-web. It uses
a static site generator for maintainability, but doesn't really use a
framework.

**Comment by scoopgracie** [comment]
Also, the static site generator is simple enough that if it has a bug, we
we could easily just fix it.

**Comment by sushain97** [comment]
It's unclear what you mean by web framework but if you mean JS framework:

The internet has plenty of resources on why something like React is helpful. They more or less all apply to html-tools with its current complexity. Have you tried solving any of the more complex issues in the html-tools issue tracker?

Feel free to attempt doing this without a framework but I'm relatively certain that will result in something that's worse in terms of readability and maintainability than the current version of html-tools, making it an entirely wasted effort for everyone involved. Or, the entire GSoC would be spent re-implementing the bits of a modern JS framework -- also wasted effort.

**Comment by scoopgracie** [comment]
I've read online articles about why to use a framework, but there are also
a lot on why not to use a framework, and they have some pretty covincing
arguments.

**Comment by scoopgracie** [comment]
I'm not saying "no way" on frameworks, I just don't see any advantages that
are enough to cancel out the disadvantages.

**Comment by sushain97** [comment]
You've mentioned exactly one disadvantage (the dependency might stop being maintained?) that I don't find at all compelling (at least for React).

Having written most of the current code in html-tools, mentored dozens of GCI tasks + multiple GSoC projects on it, I'm quite aware of what the challenges are of this project. I've also written projects with multiple contributors in plain JS, jQuery, React, VueJS and Angular. In that light, this my recommendation stands for this project.

If you'd like to go forward without a framework, as I've mentioned, that's your prerogative and I've already said my part. It's very likely I won't contribute to such a project since the existing html-tools will be effectively equivalent.

**Comment by scoopgracie** [comment]
Another advantage of vanilla is contributions. More people probably know
vanilla JS than React. (Most people that know React can probably work with
vanilla, but not everyone who can work with vanilla can work with React.)

**Comment by sushain97** [comment]
Sure, but React is relatively simple to pick up and there are literally thousands of tutorials. I'm confident that if you pick a random open-source frontend developer today, they're more likely to be familiar with React than not (and also not mind it). See https://insights.stackoverflow.com/survey/2019#technology-_-web-frameworks.

As far as students go, learning React is relatively instructive in terms of understanding strategies for state management, abstraction, etc.

**Comment by xavivars** [comment]
I'm working professionally at an e-commerce, and everyone in the industry is moving to use a framework (and I'd say mostly react) because it solves a lot of problems that you would need to solve for yourself.

So I wouldn't even consider going with Vanilla

**Comment by sushain97** [comment]
> I'm working professionally at an e-commerce, and everyone in the industry is moving to use a framework (and I'd say mostly react) because it solves a lot of problems that you would need to solve for yourself.

Yep. I've worked at Facebook, Citadel, Stripe and Palantir. **All** of them used React + (maybe TypeScript). You could counter that they write massive applications where React really shines. It's a valid argument but IMO html-tools has grown far past where it started and it now has all the complexities that React/Vue/Angular are designed for solving, even in smaller SPAs (in fact, this ends up being how most companies have segmented their applications anyway...).

**Comment by scoopgracie** [comment]
I guess I've misunderstood all the recent advances in the DOM API etc. I
though that was meant to replace frameworks.

**Comment by sushain97** [comment]
Manipulating the DOM isn't really the hard part. Sane state/interactivity management is.

**Comment by scoopgracie** [comment]
Oh, okay.

**Comment by sushain97** [comment]
For anyone interested/following along, I've gotten >80% of the way done at
https://github.com/sushain97/apertium-html-tools-v2

As of writing, the remaining work items are:
- language detection
- doc translation (parts of it)
- webpage translation (parts of it)

I'll open a huge PR sometime in the next couple weeks.

**Comment by sushain97** [comment]
Update: doc + webpage translation are complete. These are the remaining TODO:

```
❯❯❯ rg 'TODO: \[' .
./src/components/translator/LanguageSelector.tsx
17:// TODO: [parity] language detection

./src/app.tsx
29:// TODO: [parity] Add slow request -> download notifications
30:// TODO: [not before landing] Add analytics support. If anyone actually wants it?
32:// TODO: [not before landing] language filtering
```
