### ISSUE TITLE
RTL Language Translated Text alignment

### ISSUE THREAD

**Issue by MaathavanJkr** [apertium/apertium-html-tools#357]
![Screenshot (9)](https://user-images.githubusercontent.com/17196210/71591164-4d73c700-2b51-11ea-8cc1-90cac2d6c3e9.png)
here, translated text should be in the Right Alignment.

![Screenshot (10)](https://user-images.githubusercontent.com/17196210/71591189-62e8f100-2b51-11ea-9a34-630faa746634.png)
Here also the the translated text should be in right alignment. 

and the close button in the original text is also being messed up with the text in both LTR and RTL

**Comment by sushain97** [comment]
I think this works as intended. The source/target text are in whatever orientation is appropriate for that language, not the overall interface. 

On the other hand, the close button's position is intended to correspond to the interface language. This does I think result in it unfortunately overlapping sometimes.

**Comment by MaathavanJkr** [comment]
> We might want to rethink that particular decision.
Aah Thats Right. 

Sorry, The bug was when we interchange the Src and Dst Languages. See
![Screenshot (14)](https://user-images.githubusercontent.com/17196210/71765578-a7430b00-2f1c-11ea-849a-4dc71020ec7d.png)

**Comment by sushain97** [comment]
Hmm that does look like a bug.

**Comment by sushain97** [comment]
This no longer reproduces on `master`.
