### ISSUE TITLE
Mobile Translate Webpage Cancel Button

### ISSUE THREAD

**Issue by MaathavanJkr** [apertium/apertium-html-tools#358]
There isnt a button for cancel the webpage translation progress and return to normal text translation in the mobile version or small Width version.

**Comment by aryasoni98** [comment]
i would like to solve this bug

**Comment by sushain97** [comment]
This is fixed on `master`.

![image](https://user-images.githubusercontent.com/4211838/117563912-f55ea600-b05d-11eb-9963-89ac7a443bb5.png)
