### ISSUE TITLE
language selector text too low in Firefox

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-html-tools#370]
In the screenshot below, all the descenders for the letters 'q' and 'p' are chopped off in the language selector in the upper right.

![Screenshot_2020-05-21 Apertium Biypul ashıq mashinalı awdarmalaw platforması](https://user-images.githubusercontent.com/963849/82523755-164f8380-9afb-11ea-843a-51ae5254a844.png)

**Comment by sushain97** [comment]
This almost feels like a Firefox bug.

**Comment by jonorthwash** [comment]
It's oddly low for me in chromium too—just doesn't get cut off.  Maybe it's a different default behaviour that's best being more carefully specified?

**Comment by jonorthwash** [comment]
It could also be an issue with my gtk3 theme?

**Comment by sushain97** [comment]
It's just a vanilla `<select>`. Dunno how much we can configure its rendering.

**Comment by jonorthwash** [comment]
Well no, that's not strictly true.  Its `height` is specified by our css.  If that's removed, it looks okay, although a bit tall.  If `border` set to anything, then it's a vanilla select, and looks okay.

And yes, this is using my gtk3 theme's select dropdown.

**Comment by jonorthwash** [comment]
While I'm generally and advocate for leaving things to render as the user has their system configured to, it's not at all how most sites deal with localisation dropdowns.

**Comment by sushain97** [comment]
> Its height is specified by our css. If that's removed, it looks okay, although a bit tall.

Ah I didn't think of this being the potential issue. I'm fine with removing it (what's the element height when you do? Screenshot?). Maybe we can `git blame` back to why it was introduced.

**Comment by sushain97** [comment]
(It actually ends up being smaller for me without the explicit `height` -- `4x` smaller)

before:

![image](https://user-images.githubusercontent.com/4211838/82847640-1a392800-9ea4-11ea-99e8-1e8abb715e07.png)

after:

![image](https://user-images.githubusercontent.com/4211838/82847637-14dbdd80-9ea4-11ea-9919-56b63b1a0c7c.png)

**Comment by sushain97** [comment]
Hmm, I think it might have been so that the icon and select are equal heights. However, I think that was done incorrectly since per the box model, the height includes border. So if that was intent, it really should have been 23px. I think it looks like the best for me at 23px fwiw:

![image](https://user-images.githubusercontent.com/4211838/82847688-5bc9d300-9ea4-11ea-8899-e089b915bbd5.png)

**Comment by sushain97** [comment]
@jonorthwash is this fixed on `beta.apertium.org`? I incidentally rewrote the styles here to be less wacky and it looks fixed to me.

**Comment by jonorthwash** [comment]
It looks much better, at least in the browsers on the system I just tested on.

**Comment by sushain97** [comment]
Excellent. Let's close this out for now then.
