### ISSUE TITLE
"analyzation" should be "analysis" everywhere

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-html-tools#373]
From config to url, the term "analyzation" is used instead of "analysis".  But Apertium-wide otherwise "analysis" is used.  So it should be changed.

**Comment by Abhijay007** [comment]
@sushain97 is this issue is resolved ?

**Comment by sushain97** [comment]
Sure looks like it: https://github.com/search?q=repo%3Aapertium%2Fapertium-html-tools%20analyzation&type=code
