### ISSUE TITLE
Swap button should swap text as well

### ISSUE THREAD

**Issue by khannatanmai** [apertium/apertium-html-tools#376]
The swap button on the website should swap the text in the text boxes as well so that the button can be used for back translation as it is on Google Translate. Right now there's not much use of the button.

**Comment by jonorthwash** [comment]
I think an argument could be made for either behaviour.  I have need of both from time to time, so am happy either way.

**Comment by khannatanmai** [comment]
You would need to just switch the languages and not the text if you somehow by mistake put text in the wrong box or something. The argument for switching the text as well, apart from back translation could also be if I wanna translate from A to B to C, so I translate A to B, then switch and then change target language to C. Is there some use case I'm missing for the first functionality?

**Comment by sushain97** [comment]
I'm +1 to us behaving the same way that Google Translate does. I imagine they've done some amount of user research to figure out what behavior folks find most useful/intuitive.

**Comment by CipherGirl** [comment]
I would like to try working on this issue. I am a GSoC aspirant.
