### ISSUE TITLE
URL to be translated not recognised

### ISSUE THREAD

**Issue by khannatanmai** [apertium/apertium-html-tools#384]
https://frp.wikipedia.org/wiki/Histouère_de_l’ârt doesn't work on beta.apertium.org when I try to translate from Arpitan to French. However, https://frp.wikipedia.org/wiki/Histou%C3%A8re_de_l%E2%80%99%C3%A2rt works. It's something to do with the special characters in the url.

I need to put beta.apertium.org in my system demonstration in, so I'd appreciate it if we can try to fix it asap.

**Comment by TinoDidriksen** [comment]
https://github.com/apertium/apertium-html-tools/blob/master/assets/js/util.js#L186 needs to be adjusted to allow for Unicode. Also seems that regex has an allowlist of TLDs, which is fundamentally broken because new TLDs are created all the time. This can be greatly simplified and improved.

**Comment by TinoDidriksen** [comment]
In fact, the linked SO post says the TLD list was "current as of June 2007" ... that's ancient history. I would probably reduce that regex to `/^https?:\/\/\S+\s*$/i`

**Comment by coding-CEO** [comment]
> https://github.com/apertium/apertium-html-tools/blob/master/assets/js/util.js#L186 needs to be adjusted to allow for Unicode. Also seems that regex has an allowlist of TLDs, which is fundamentally broken because new TLDs are created all the time. This can be greatly simplified and improved.

Hi, I am new to this repo and open source contribution.
In my opinion we should validate url using the URL builtin package of node.js
https://nodejs.org/api/url.html#url_new_url_input_base

This will throw error if url is invalid and this will also format url like this (https://frp.wikipedia.org/wiki/Histouère_de_l’ârt) to url like this (https://frp.wikipedia.org/wiki/Histou%C3%A8re_de_l%E2%80%99%C3%A2rt)

Example code:
> const URL = require('url').URL; 
let out = new URL("https://frp.wikipedia.org/wiki/Histouère_de_l’ârt"); // This line will throw error if url is InValid
console.log(out.href);

**Comment by sushain97** [comment]
apertium-html-tools does not have a backend, definitely not a Node one. Any
validation should occur on the client side.

**Comment by coding-CEO** [comment]
I saw package.json in code so I thought it is using node.js. My bad
