### ISSUE TITLE
Add the option to copy and erase text in the web.

### ISSUE THREAD

**Issue by wuniversales** [apertium/apertium-html-tools#391]
It can see an example working in this web:
https://libretranslate.com/
Greetings

**Comment by TinoDidriksen** [comment]
So, just two buttons? That should be rather trivial.

**Comment by sushain97** [comment]
This seems... quite unnecessary? At best, it's redundant with your operating system's standard text editing features and at worst it introduces noise to an already busy interface.

**Comment by TinoDidriksen** [comment]
It is strictly speaking unnecessary, but it's what mobile users expect. Long-pressing and using menus is just so tedious, don't'ya'know. I figure if someone wanted to add them they could, but it's not something we need to prioritize.

**Comment by Aayush-hub** [comment]
@TinoDidriksen It seems interesting to me. Can I work on this?

**Comment by TinoDidriksen** [comment]
Anyone can work on anything in open source. Just do the work and submit a PR. And the fact that none of us took care of this rather trivial task is a good indicator that we're not working on it in parallel.
