### ISSUE TITLE
Can't run make command

### ISSUE THREAD

**Issue by Aayush-hub** [apertium/apertium-html-tools#392]
After trying very hard I am still coming with error below. Can anyone help me to solve it?

![11](https://user-images.githubusercontent.com/65889104/111868847-5218db00-89a2-11eb-815c-2b6c7eb4d17b.png)

**Comment by TinoDidriksen** [comment]
We don't support building on Windows. Use WSL or a VM or Docker.

**Comment by Aayush-hub** [comment]
@TinoDidriksen Thanx for the help!
