### ISSUE TITLE
Add noscript warning

### ISSUE THREAD

**Issue by flammie** [apertium/apertium-html-tools#414]
I use noscript extension on chromium and beta.apertium.org opens currently totally empty screen. At least a short informative message would be nice, but I think that just translating plain text snippet should not really need javascript...

**Comment by sushain97** [comment]
Happy to approve a PR which adds a noscript tag.

It has never been an objective of this repository to support no-JS functionality and I don't expect that it ever will be given its feature set and goals.

**Comment by flammie** [comment]
sounds good, I'm not very good at modern web stuffs but if I read the code correctly it's probably not easy to make the noscript part localisable?

**Comment by sushain97** [comment]
> it's probably not easy to make the noscript part localisable?

I can't see how that would be possible since you can't change the text or redirect the user based on their locale without using JS.
