### ISSUE TITLE
Preference selection menu could be more readable

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-html-tools#435]
![image](https://user-images.githubusercontent.com/56868/151783442-44697f41-baa5-4e16-94ff-ccc1f2027e5b.png)

Even worse on mobile (can't even scroll to the right to see the rest – yes I know that's my fault ;)):

![image](https://user-images.githubusercontent.com/56868/151784030-2c5e6f98-d3b9-4040-b4df-7906e52ec8c3.png)

One line per preference might improve things. Perhaps truncation with a `…`-toggle (hide/show full description) for the long ones.

**Comment by unhammer** [comment]
@sushain97 it's quite bad with all the preferences now :) If one simple changes `div.dropdown-menu.show` to have `position:fixed; height:100%;width:100%` it's quite usable again (but needs an :x: in the upper right to dismiss), but I bet you have about 1000x more experience in react-bootstrap than me – is that easily doable there?

**Comment by sushain97** [comment]
I'll give it a look this weekend!
