### ISSUE TITLE
shows %%UNAVAILABLE%%  strings

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-html-tools#444]
shouldn't the "%%UNAVAILABLE%% " be stripped? (it's added by the l10n tools scripts)

see e.g.
https://beta.apertium.org/index.sme.html#translation?dir=nob-nno&q=vi%20liker%20%C3%A5%20synge%20mens%20dere%20bygger

**Comment by sushain97** [comment]
Good catch... I must have regressed this feature. Good thing we had tests before (/s)!

**Comment by sushain97** [comment]
Fixed in 4fce5049a4c48bcd3f6208374b21fd1a561e1e62!
