### ISSUE TITLE
request: friendlier build error messages

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-html-tools#449]
* If no translation modes are found and the default mode is translation, then the user gets a blank page on trying to access HTML Tools.  The only clue about what the problem is is a js console message about no pair being available.
* If APy is inaccessible but some other http endpoint exists there's a very scary-looking build crash, that only reports error 405.  Instead it should complain about no APy existing at that endpoint.

**Comment by sushain97** [comment]
LMK if this doesn't look better, @jonorthwash .

**Comment by jonorthwash** [comment]
The code looks promising.  To know for sure, I'll have to either wait until I run into these things again, or emulate these conditions again—either way it may be a while.  In the meantime, thanks!
