### ISSUE TITLE
Duplicate source languages in selector

### ISSUE THREAD

**Issue by unhammer** [apertium/apertium-html-tools#461]
I think I broke it:
![bilde](https://user-images.githubusercontent.com/56868/223662297-5677261e-b1a2-4539-93a1-cd503eee380e.png)
Not sure how.

Then I clicked ctrl+shift+R:
![bilde](https://user-images.githubusercontent.com/56868/223662483-e0c42ffa-28be-4745-94a2-ea51a615ec4f.png)

and if I select nynorsk there:

![bilde](https://user-images.githubusercontent.com/56868/223662635-b0dd4c61-328b-40af-a8b8-cb1b6454bedb.png)

**Comment by sushain97** [comment]
Might be useful to publish your local storage for purposes of debugging.

**Comment by unhammer** [comment]
```
{
  "tgtLang": "\"nno\"",
  "generatorText": "\"\"",
  "instantTranslation": "true",
  "markUnknown": "true",
  "recentTgtLangs": "[\"nno\",\"dan\",\"eng\"]",
  "analyzerText": "\"\"",
  "translationChaining": "false",
  "srcLang": "\"nob\"",
  "translationPrefs": "{\"nob-nno\":{\"ggj_gg\":true,\"medan_mens\":true,\"kløyvd_inf\":false,\"infa_infe\":true,\"løk_lauk\":true,\"røyndom_røynd\":false,\"røyndom_verkelegheit\":true,\"de_dokker\":true}}",
  "srcText": "\"Se. \\nVindu. \\nFestet.\\nSamtaler.\\n\\n\"",
  "recentSrcLangs": "[\"nob\",\"nno\",\"nno\"]",
  "locale": "\"nno\"",
  "generatorLang": "\"ady\"",
  "analyzerLang": "\"oci_gascon\""
}
```

**Comment by sushain97** [comment]
Huh, I see why the UI would behave this way with the given local storage. I'm not sure how you ended up with that config, though...

**Comment by unhammer** [comment]
would the state be cleaned by a uniq on the recentSrcLangs list?

**Comment by sushain97** [comment]
https://github.com/apertium/apertium-html-tools/commit/3470f11fc7c15ee273981cb445495324d9c9b673 should fix it.

Although, I'm still confused as to how this happened since this should prevent it:
https://github.com/apertium/apertium-html-tools/blob/3470f11fc7c15ee273981cb445495324d9c9b673/src/components/translator/Translator.tsx#L118

**Comment by unhammer** [comment]
Thanks! Yeah I have no idea :-/
