### ISSUE TITLE
Google Summer of code in the about section behaves as a link

### ISSUE THREAD

**Issue by 456535688765** [apertium/apertium-html-tools#462]
What Happens: The Google summer of code acts like a link instead of staying unchanged.
while hovering it changes its state and it gets underlined

Solution : need some changes in the img section

**Comment by TinoDidriksen** [comment]
The actual bug is that https://summerofcode.withgoogle.com/static/img/summer-of-code-logo.svg is now a 404.

Could replace it with https://summerofcode.withgoogle.com/assets/media/logo.svg though depending on 3rd party images is a bad idea.

**Comment by 456535688765** [comment]
should I replace it with https://summerofcode.withgoogle.com/assets/media/logo.svg this image

**Comment by TinoDidriksen** [comment]
Looks like other assets are in https://github.com/apertium/apertium-html-tools/tree/master/src/components/footer/img, so I'd say it should go there.

**Comment by 456535688765** [comment]
So do I make a change in the code base or need to upload the image file here  https://github.com/apertium/apertium-html-tools/tree/master/src/components/footer/img

**Comment by 456535688765** [comment]
Ok Got it Adding the Google summer of code img to this section https://github.com/apertium/apertium-html-tools/tree/master/src/components/footer/img

**Comment by 456535688765** [comment]
Sharing the PR 
Thank you @TinoDidriksen for your help

**Comment by 456535688765** [comment]
Hey @TinoDidriksen can you help me with the merging process

**Comment by hazemk537** [comment]
help in merge plz,, https://github.com/apertium/apertium-html-tools/pull/464

**Comment by 456535688765** [comment]
Thhe issue is not solved yet @hazemk537
![Screenshot (230)](https://user-images.githubusercontent.com/92295764/224478140-774a8a55-966f-4451-a9f8-316a3b56ecb7.png)

**Comment by hazemk537** [comment]
@456535688765 we can do it inshaallah

**Comment by 456535688765** [comment]
I have resolved this Google Summer of code in the about section behaves as a link #462 problem but getting issues with the formatting of the code

**Comment by 456535688765** [comment]
Can you help me @TinoDidriksen?

**Comment by 456535688765** [comment]
![Screenshot (232)](https://user-images.githubusercontent.com/92295764/224491788-ba8fed67-5bd8-4735-a786-3b6140cd7f6d.png)
resolved

**Comment by 456535688765** [comment]
should I start with the PR

**Comment by TinoDidriksen** [comment]
Yes, I don't know why you closed the PR.

**Comment by 456535688765** [comment]
I added some modules by mistake

**Comment by hazemk537** [comment]
- any help wto detect the problem in checks here 
-   https://github.com/apertium/apertium-html-tools/pull/467/checks
