### ISSUE TITLE
footer disapear on lower window size

### ISSUE THREAD

**Issue by hazemk537** [apertium/apertium-html-tools#468]
suggest : making new break point to solve the disappering footer

![image](https://user-images.githubusercontent.com/63047860/226570246-f21f2a7b-5551-465d-94f0-cd766f8c0a14.png)

**Comment by AnkitLimone** [comment]
Hello 
I can solve this issue. How can I contribute?

**Comment by TinoDidriksen** [comment]
@AnkitLimone, anyone is free to solve a problem and open a PR with the solution.
