### ISSUE TITLE
Build should not rely on git

### ISSUE THREAD

**Issue by TinoDidriksen** [apertium/apertium-html-tools#477]
`git describe --tags --always` at https://github.com/apertium/apertium-html-tools/blob/master/build.ts#L65 and potentially other places should be removed. A build must not rely on vcs tools.

Also, the build instructions [don't say to install git](https://github.com/orgs/apertium/discussions/40).

**Comment by satti-hari-krishna-reddy** [comment]
@TinoDidriksen  Would it be acceptable to simplify this process by directly using the version from package.json ?
