### ISSUE TITLE
The copy option is on the  translated text

### ISSUE THREAD

**Issue by Sudheendra1925** [apertium/apertium-html-tools#488]
![Screenshot 2024-02-23 211141](https://github.com/apertium/apertium-html-tools/assets/153935508/3e8590e3-abb9-4b37-be01-c4454315471a)
its a small one we can fix it

**Comment by Sudheendra1925** [comment]
Can I  Try to fix That

**Comment by unhammer** [comment]
go ahead :)

**Comment by shivamgupta2020** [comment]
![image](https://github.com/apertium/apertium-html-tools/assets/91847638/852b4a27-6c83-4a71-9fd2-33ffc75e2a19)
In RTL languages cross and copy buttons are making problem, I think we can shift cross and copy to left according to languages (RTL or LTR) to  avoid this overlapping.
@unhammer can I try on this issue?

**Comment by unhammer** [comment]
no need to ask, just try it and send a PR
