### ISSUE TITLE
Input box and output area should work more sensibly for analysis when RTL text is involved

### ISSUE THREAD

**Issue by jonorthwash** [apertium/apertium-html-tools#49]
Currently this is what it looks like:
![screenshot_2016-02-01_021343](https://cloud.githubusercontent.com/assets/963849/12711624/618343ca-c88f-11e5-8cf7-9e353b48ae7f.png)

The text box should at the very least have the text right-justified, and the output should probably be flipped.  I'm not sure what to do about mixing RTL text with LTR tags....

**Comment by Axle7XStriker** [comment]
I tried to recreate the bug but I think this issue has already been resolved. And if not can anyone tell me what still remains in this issue.

**Comment by sushain97** [comment]
Hm, it's mostly resolved. Seems like the button has lost its alignment, though:

![image](https://user-images.githubusercontent.com/4211838/37629811-eaa721ba-2bae-11e8-97d8-78f107a690da.png)
