### ISSUE TITLE
when starting the web server on web browser to view the website it is showing Beta over Apertium.

### ISSUE THREAD

**Issue by Sahilkumar19** [apertium/apertium-html-tools#490]
![Screenshot 2024-02-25 194655](https://github.com/apertium/apertium-html-tools/assets/124178990/d321965d-fbbe-4b43-8288-f6ba9736448c)

is it a valid issue? or it is Beta version.

**Comment by TinoDidriksen** [comment]
That's determined by `config.ts` and defaults to Beta. The Release config is in https://github.com/apertium/apertium-website
